# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: w7pool

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    # - task: Npm@1
    #   inputs:
    #     command: custom
    #     customCommand: 'sudo npm install -g npm@latest'
    #   displayName: 'Upgrade npm to latest version'
    
    - task: CmdLine@2
      inputs:
        script: 'sudo npm install npm@latest -g'
    
    - task: CmdLine@2
      inputs:
        script: 'npm -v'
    

