# --
# - hosts: localhost
#   vars:
#     resource_group: "{{rg}}"
#     scaleset_name: "{{ resource_group }}-vmss"
#     loadbalancer_name: "{{ resource_group }}-lb"
#     admin_username: "{{ resource_group }}"
#     admin_password: "{{pass}}"
#   tasks:
#   - include: get-hosts-tasks.yml

- name: run on all hosts
  hosts: "stage"
  tasks:
  
    - name: install unzip
      shell: 'npm install pm2@latest -g '
      become: yes
  
    - name: install node 14 latest
      shell: 'curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs'
      become: yes
      
    - name: update npm to latest
      shell: 'npm install npm@latest -g '
      become: yes
      
    - name: install pm2
      shell: 'npm install pm2@latest -g '
      become: yes

#     - name: pm2 delete all
#       shell: pm2 delete all
#       ignore_errors: yes

#     - name: pm2 start npm --name "weight tracker" -- run dev
#       shell: pm2 start npm --name "weight tracker" -- run dev
#       args:
#         chdir: ~/app

#     - name: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u stas --hp /home/stas
#       shell: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u stas --hp /home/stas
#       become: yes

#     - name: pm2 save
#       shell: pm2 save --force
