---
- name: run on resource group
  hosts: "{{ rg }}"
  gather_facts: false
  ignore_unreachable: true
  tasks:

    - name: update system
      shell: 'apt-get update && apt-get upgrade -y'
      become: yes
  
    - name: install node 14
      shell: 'curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs'
      become: yes
      
    - name: install unzip
      shell: 'sudo apt-get install unzip'
      become: yes
      
    - name:  copy artifact to remote
      copy:
        src: "{{ playbook_dir }}/../../_App_CI/wt-app/wt-app.zip"
        dest: ~/
        
    - name: unzip artifact
      shell: 'mkdir app && unzip wt-app.zip -d ~/app'
      
    - name: Creating a file with content
      copy:
        dest: "~/app/.env"
        content: |
          # Host configuration
          PORT=8080
          HOST=0.0.0.0
          HOST_URL=http://{{ hostvars['st-lb1'].ansible_host }}:8080
          COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
          NODE_ENV=development
          
          # Okta configuration
          OKTA_ORG_URL={{ oip }}
          OKTA_CLIENT_ID={{ oid }}
          OKTA_CLIENT_SECRET={{ ocs }}
          
          # Postgres configuration
          PGHOST={{ pgn }}-pg-f-server.postgres.database.azure.com
          PGUSERNAME={{ pgu }}
          PGDATABASE=postgres
          PGPASSWORD={{ pgp }}
          PGPORT=5432

    - name: update npm to latest
      shell: 'npm install npm@latest -g '
      become: yes
      
    - name: install pm2
      shell: 'npm install pm2@latest -g '
      become: yes

#     - name: pm2 delete all
#       shell: pm2 delete all
#       ignore_errors: yes

#     - name: pm2 start npm --name "weight tracker" -- run dev
#       shell: pm2 start npm --name "weight tracker" -- run dev
#       args:
#         chdir: ~/app

#     - name: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u "{{ user }}" --hp /home/"{{ user }}"
#       shell: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u "{{ user }}" --hp /home/"{{ user }}"
#       become: yes

#     - name: pm2 save
#       shell: pm2 save --force
